### ISSUE TITLE
Applying Continuous Integration

### ISSUE THREAD

**Issue by Weslin-0101** [FKarl/short-text-classification#2]
Hi, how are you doing? I'm a software engineer at the University of Brasilia, and we worked on a project related to Software Evolution Management. We have added new files to your project that will help you with future dependencies.

We have included the following in your project:

- Dockerfile to containerize your application and database.
- Poetry to manage project dependencies, creation, and package distribution.
- Flake8 and Black to improve code quality and maintain consistent code style.
- Sphinx to generate documentation for your project.
- GitHub Actions Workflows to configure continuous integration pipelines.

Here is the link to your project: https://github.com/Weslin-0101/Projeto-Individual-GCES

Note: Currently, the repository will remain private until after June 28th due to the college work submission rules.

**Comment by FKarl** [comment]
Hi there! Thank you for reaching out and for your contributions to the project. I will definitely take a look at your repository.
